# Wieso hoch und runterfahren des Containers wenn settings geändert werden
# DataPortalAdmin hat keine rechte
services:
  dataportal-backend:
    container_name: dataportal-backend
    image:  ghcr.io/medizininformatik-initiative/feasibility-backend:latest
    ports:
      - "8090:8090"
    depends_on:
      dataportal-postgres:
        condition: service_started
      elastic-search-init:
        condition: service_completed_successfully
    environment:
      JAVA_OPTS: ""
      QUERYRESULT_PUBLIC_KEY: "MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA1lWOfXzE/mUEPitNLxsDMtjERJGVhS8gP1WmuHPvjPxUOQyod4EbJcbJlkBqLqpaIs8Buy3gcbJvIPERdG1N1BSZ8NOKOtRubioKf30JwnLdZAae3vJAzRC3h42OPM3fohZCXMxbrju+KM0ZUIrLEXKEDMHQWfevCQCxeixvXVYpfXlkJIBGaWz4cDgEOiiwhU87AMzGZwjAIHvr4oTF/uHg6+C3Mdx0m8WLtygTiEixJegMb/txR+4gNVYrzpm5BwDUU7Qxy3nTUDYZLlTGeP9MBFWW+W87IHzgP+OFr3ZKMEkAPU0R1lqXFZCYcgZHGA5He2W701isnqkKIQT8ePOH43ZOXo3S34Pqw5oQ4Q2kPubp1wgZWw0VtEiZDtlwqUJ+r3CigU7NAFM5JnC/skiIBKetbWoNm1JPEfGOTrgjHD2uo82jSO8tV45LNH1EaR2+5UWSFZyDvTayLZsxsVlRFXJKgQJDI344R6lhGbLXbhqCuPzeQaHr1XGCKAtdAgMBAAE="
      # ----- app
      QUERY_VALIDATION_ENABLED: "true"
      CQL_TRANSLATE_ENABLED: "false"
      FHIR_TRANSLATE_ENABLED: "false"
      API_BASE_URL: "http://localhost:8090/api/"
      ALLOWED_ORIGINS: "http://localhost:4200"
      QUERYRESULT_EXPIRY_MINUTES: 5
      # ---- db config
      DATABASE_HOST: "dataportal-postgres"
      DATABASE_PORT: 5432
      DATABASE_USER: "dataportaluser"
      DATABASE_PASSWORD: "dataportalpw"
      DATABASE_DBNAME: "dataportal"
      # ---- auth
      KEYCLOAK_ENABLED: "true"
      KEYCLOAK_ALLOWED_ROLE: "DataportalUser"
      KEYCLOAK_POWER_ROLE: "DataportalPowerUser"
      KEYCLOAK_ADMIN_ROLE: "DataportalAdmin"
      KEYCLOAK_BASE_URL_ISSUER: "http://localhost:8080"
      KEYCLOAK_BASE_URL_JWK: "http://auth:8080"
      KEYCLOAK_REALM: "dataportal"
      #---- Direct broker
      BROKER_CLIENT_MOCK_ENABLED: "true"
      BROKER_CLIENT_DIRECT_ENABLED: "false"
      BROKER_CLIENT_DIRECT_USE_CQL: "false"
      BROKER_CLIENT_OBFUSCATE_RESULT_COUNT: "false"
      FLARE_WEBSERVICE_BASE_URL: "http://flare:8080"
      CQL_SERVER_BASE_URL: "http://blaze:8080/fhir"
      # ---- privacy
      PRIVACY_QUOTA_SOFT_CREATE_AMOUNT: 3
      PRIVACY_QUOTA_SOFT_CREATE_INTERVAL: PT1M
      PRIVACY_QUOTA_HARD_CREATE_AMOUNT: 50
      PRIVACY_QUOTA_HARD_CREATE_INTERVAL: P7D
      PRIVACY_QUOTA_READ_SUMMARY_POLLINGINTERVAL: PT10S
      PRIVACY_QUOTA_READ_DETAILED_OBFUSCATED_POLLINGINTERVAL: PT10S
      PRIVACY_QUOTA_READ_DETAILED_OBFUSCATED_AMOUNT: 3
      PRIVACY_QUOTA_READ_DETAILED_OBFUSCATED_INTERVAL: PT2H
      PRIVACY_THRESHOLD_RESULTS: 0
      PRIVACY_THRESHOLD_SITES: 0
      # ---- Elastic Search
      ELASTIC_SEARCH_ENABLED: "true"
      ELASTIC_SEARCH_HOST: dataportal-elastic:9200
      ELASTIC_SEARCH_FILTER: context,terminology,kds_module
      # ---- logging
      LOG_LEVEL_SQL: "warn"
      LOG_LEVEL: "warn"
    restart: unless-stopped
    volumes:
      - ./secrets:/opt/dataportal-security

  dataportal-postgres:
    image: 'postgres:16-alpine'
    container_name: dataportal-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dataportaluser"
      POSTGRES_PASSWORD: "dataportalpw"
      POSTGRES_DB: "dataportal"

  dataportal-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: dataportal-elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      node.name: es01
      cluster.name: elasticsearch
      xpack.security.enabled: "false"

  elastic-search-init:
    depends_on:
      - dataportal-elastic
    image: ghcr.io/medizininformatik-initiative/dataportal-es-init:1.2
    container_name: integration-test_elastic-search-init
    environment:
      ES_HOST: dataportal-elastic
      LOCAL_PATH: /tmp/mounted_onto.zip
    volumes:
      - type: bind
        source: "./ontology/elastic.zip"
        target: "/tmp/mounted_onto.zip"
        read_only: true

  auth-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "keycloakdb"
      POSTGRES_USER: "keycloakdbuser"
      POSTGRES_PASSWORD: "keycloakdbpw"
    volumes:
      - dataportal-auth-db:/var/lib/postgresql/data

  auth:
    image: keycloak/keycloak:26.2
    container_name: keycloak-auth
    command: ["start", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://auth-db:5432/keycloakdb"
      KC_DB_USERNAME: "keycloakdbuser"
      KC_DB_PASSWORD: "keycloakdbpw"
      KEYCLOAK_ADMIN: "keycloakadmin"
      KEYCLOAK_ADMIN_PASSWORD: "keycloak"
      KC_HOSTNAME: "http://localhost:8080"
      KC_LOG_LEVEL: "info"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
      - "9003:9000"
    volumes:
      - ./keycloak-init/dataportal-realm.json:/opt/keycloak/data/import/realm.json:ro
    depends_on:
      - auth-db

volumes:
  dataportal-auth-db:
