name: E2E Tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Download Dataportal Backend Image
        uses: actions/download-artifact@v4
        with:
          name: backend-image
          path: /tmp

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Load Dataportal Backend Image
        run: docker load --input /tmp/dataportalBackend.tar

      - name: Download ontology files from GitHub
        run: .github/scripts/download-and-unpack-ontology.sh

      - name: Run Dataportal Backend with Database, Elasticsearch, Keycloak and Blaze
        run: docker compose -f .github/integration-test/docker-compose.yml up -d

      - name: Wait for Dataportal Backend
        run: .github/scripts/wait-for-url.sh http://localhost:8091/actuator/health

      - name: Check if Dataportal Backend is correctly running with the user with id 10001
        run: .github/scripts/check-if-running-as-user-10001.sh

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
