name: E2E Tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
      - name: Checkout backend integration test config
        uses: actions/checkout@v4
        with:
          repository: medizininformatik-initiative/feasibility-backend
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          path: backend-integration-config

      - name: Debug List cloned files
        run: |
          echo "Root directory:"
          ls -la
          echo "backend-integration-config/.github/integration-test:"
          ls -la backend-integration-config/.github/integration-test


      - name: Build and start integration services
        run: |
            docker compose -f backend-integration-config/.github/integration-test/docker-compose.yml up -d --build
      - name: Wait for backend health
        run: |
          .github/scripts/wait-for-url.sh http://localhost:8091/actuator/health

      - name: (Optional) Check backend user setup
        run: |
          .github/scripts/check-if-running-as-user-10001.sh

