name: E2E Tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  cypress-run:
    runs-on: ubuntu-24.04
    env:
      ONTOLOGY_GIT_TAG: v3.8.1 # Or dynamically set it
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare ontology files
        run: |
          chmod +x .github/scripts/setup-ontology.sh
          .github/scripts/setup-ontology.sh

      - name: Start Docker Compose
        run: docker compose -f cypress/docker/docker-compose.yml up -d

      - name: Check backend health with curl (wait until ready)
        run: |
          max_attempts=20
          attempt=0
          until curl --fail http://localhost:8091/actuator/health; do
            attempt=$((attempt+1))
            if [ $attempt -ge $max_attempts ]; then
              echo "Backend did not become healthy after $max_attempts attempts"
              exit 1
            fi
            echo "Waiting for backend to be healthy... attempt $attempt"
            sleep 5
          done
          echo "Backend is healthy!"



      - name: Check backend health with curl
        run: |
          curl --fail http://localhost:8091/actuator/health

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome