jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      QUERYRESULT_PUBLIC_KEY: ${{ secrets.QUERYRESULT_PUBLIC_KEY }}
      QUERYRESULT_PRIVATE_KEY: ${{ secrets.QUERYRESULT_PRIVATE_KEY }}
      QUERYRESULT_ENCRYPTION_KEY: ${{ secrets.QUERYRESULT_ENCRYPTION_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start integration services
        run: |
          docker-compose -f feasibility-backend/.github/integration-test/docker-compose.yml pull backend
          docker-compose -f feasibility-backend/.github/integration-test/docker-compose.yml up -d

      - name: Wait for backend health
        run: |
          .github/scripts/wait-for-url.sh http://localhost:8091/actuator/health

      - name: (Optional) Check backend user setup
        run: |
          .github/scripts/check-if-running-as-user-10001.sh

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
